/* Read-only presentation over the incident and archived reports. */
(function(root){
  'use strict';
  const time=n=>{n=420+Math.round(n);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;};
  const active=(s,kind,location)=>s.resources.filter(r=>r.kind===kind&&r.status==='assigned'&&r.location===location&&r.capable&&r.verified);
  function sourcing(s){return root.RR17.VENDORS.filter(v=>v.capable).map(v=>({id:v.id,name:v.id==='internal'?'Move the channel team':v.id==='harbor'?'Bring in the fast team':'Use the regional team',supplier:v.name,cost:v.cost,eta:time(s.minute+v.eta),minutes:6,tradeoff:v.id==='internal'?'Arrives first; Channel Recovery loses monitoring.':v.id==='harbor'?'Keep channel monitoring; pay for faster source help.':'Keep channel monitoring; pay less, wait longer.',uncertainty:s.difficulty==='advanced'&&v.id==='regional'?'Quoted ETA; dispatch may revise the road transfer.':'Confirmed mobilization estimate.'}));}
  function containment(s){return ['Marsh inlet','Channel'].map(location=>({location,boom:s.resources.filter(r=>r.kind==='boom'&&r.status==='assigned'&&r.location===location).map(r=>r.id),skimmers:s.resources.filter(r=>/skimmer/.test(r.kind)&&r.capable&&r.status==='assigned'&&r.location===location).map(r=>r.id),monitoring:active(s,'monitor',location).length>0,demand:location==='Channel'?s.intel.channelDemand:s.intel.marshDemand}));}
  function crewLine(s){const r=s.resources.find(r=>r.id===s.flags.monitorId);return s.safetyHold?{from:'Entry Group / Source berth',text:r?.status==='en_route'?`“We’re holding at the berth. ${r.name} is due at ${time(r.eta)}.”`:s.minute>=180&&!active(s,'relief','Source berth').length?'“Our duty limit is reached. We need the relief crew before source work can resume.”':'“We are holding here. Monitoring and required crew coverage must be verified.”'}:{from:'Entry Group / Source berth',text:'“Monitoring is in place. We can support source work while crew coverage holds.”'};}
  function scene(s,selected){const t=s.tasks.find(t=>t.id===selected)||s.tasks.find(t=>s.queue.includes(t.id)&&t.available);return {task:t,crew:crewLine(s),areas:containment(s),sourceHeld:s.safetyHold,clock:time(s.minute),reserve:s.resources.filter(r=>r.kind==='boom'&&r.status==='available').length,failed:s.resources.filter(r=>r.kind==='boom'&&r.status==='out_of_service').map(r=>r.id),choices:sourcing(s)};}
  function result(s,index){
    const e=s.events[index]||{},h=s.history.find(h=>h.eventId===e.id),condition=e.type==='period_start'?s.history.findLast(h=>h.source==='condition'&&h.minute===e.minute):null;
    if(condition)return {title:condition.action==='Reserve deployed'?'The section failed. Your line kept its coverage.':'A section failed. Its place is still empty.',change:condition.change,line:condition.consequence,carry:condition.constraint,from:'Operations / Containment line'};
    if(h)return {title:h.action==='Monitoring source'?'Help is committed. The crew still waits.':h.action==='Containment allocation'?'This is the compromise you made.':h.action==='Next-period forecast'?'The next watch will inherit this choice.':h.action,change:h.change,line:h.consequence,carry:h.constraint,from:h.source==='team'?'Your incident team':'Your response'};
    const arrived=s.events.filter(x=>x.type==='resource_arrival'&&x.minute>s.minute-(e.minutes||0)&&x.minute<=s.minute);
    return {title:arrived.length?'Help has reached the incident.':e.type==='period_start'?'The next period begins.':'The incident moves forward.',change:arrived.map(a=>`${a.resourceId} arrived at ${time(a.minute)}.`).join(' ')||e.condition||e.consequence||'Assignments and consequences carried forward.',line:crewLine(s).text,carry:s.intel.currentGaps[0]||'Keep the resource picture with the next watch.',from:arrived.length?'Staging':'Planning'};
  }
  function decision(s,t){
    const kind=t?.kind;
    const support=s.flags.supportPlan?.relief===undefined?'relief':'waste';
    const info={
      allocation:{title:'Six sections. Two places that need them.',from:'Operations / Containment',text:`The ${s.intel.priorityArea==='marsh'?'marsh inlet':'working channel'} has the higher immediate consequence. Marsh needs ${s.intel.marshDemand} sections; channel needs ${s.intel.channelDemand}. Six are available.`,instruction:'Place the sections. A spare protects no water now, but can replace a failed coupling.',minutes:10},
      reconcile:{title:'One board. Two different accounts.',from:'Resources Unit / Equipment status',text:'Staging lists SK-02 as available. Maintenance’s newer signed inspection reports a failed pump seal. Operations is asking whether it can fill the marsh assignment.',instruction:'Reconcile the status and the evidence you will carry forward. A status change cannot repair the pump.',minutes:6},
      reassign:{title:'One working skimmer. Two recovery fronts.',from:'Operations / Assignment decision',text:'SK-01 is working the channel. The marsh also needs recovery support; SK-02 cannot work. Moving SK-01 opens a channel gap. A contractor preserves both assignments after its travel time.',instruction:'Operations has authorized these three recommendations. Choose what the response can afford to leave waiting.',minutes:8},
      forecast:{title:support==='relief'?'Who takes over when this crew stops?':'Where does the recovered waste go?',from:'Logistics / Next operational period',text:support==='relief'?`Source crews reach their duty limit at 10:00. A relief crew costs $1,400 and takes 55 minutes: ordered now, ETA ${time(s.minute+55)}.`:`One waste package supports recovery through handover. It costs $1,000 and takes 40 minutes: ordered now, ETA ${time(s.minute+40)}. Without capacity, recovery slows after 09:30.`,instruction:'Order the need, keep a contingency package, or accept the gap. Outstanding orders are never counted as present.',minutes:4,support},
      relief:{title:'The next crew has not taken over.',from:'Staging / Source relief',text:'Source work pauses at 10:00 without a verified relief crew at the berth. Check arrivals or order the missing support before handing over.',instruction:'You can recover this gap or record it for the incoming watch.',minutes:7},
      checkin:{title:'The arriving package needs a decision.',from:'Staging / Reception exception',text:'Arrival has been recorded, but the team cannot be assigned automatically. Verify the actual capability and required check-in evidence.',instruction:'Hold an unsuitable package at staging. A qualified replacement can be ordered after the discrepancy is recorded.',minutes:8},
      handover:{title:'Your watch ends. Their response continues.',from:'Incoming Resources Unit',text:'They inherit the actual assignments, outstanding orders and remaining gaps below. Routine verified records go with them.',instruction:'Put the most limiting condition first. You can still resolve a resource gap before making the handover.',minutes:8}
    };
    return info[kind]||{title:t?.title||'Carry the response forward',from:t?.from||'Planning',text:t?.summary||'',instruction:'Use the current incident record.',minutes:0};
  }
  function recovery(s,a){
    if(a.type==='order-monitor'){const v=root.RR17.VENDORS.find(v=>v.id===a.vendor);return {title:`Order ${v.name} for ${a.assignment}`,detail:`$${v.cost.toLocaleString('en-US')} · quoted ETA ${time(s.minute+v.eta)} · 6 incident minutes${s.difficulty==='advanced'&&v.id==='regional'?' · regional transfer may slip':''}. Arrival and verification still required.`};}
    if(a.type==='order-support'){const relief=a.kind==='relief';return {title:`Order the missing ${a.kind} support`,detail:`$${relief?'1,400':'1,000'} · ETA ${time(s.minute+(relief?55:40))} · 8 incident minutes. The gap remains until arrival.`};}
    const choices={'correct-status':['Correct SK-02 to out of service','6 incident minutes. Cite the signed inspection; the failed pump stays unavailable.'],'correct-relief':['Assign verified relief to the source','7 incident minutes. Move the arrived crew to Source berth.'],'correct-checkin':['Complete the source team’s reception','8 incident minutes. Verify the arrived atmospheric team and its assignment.'],'receive-monitor':['Receive '+(a.resourceId||'the monitoring team'),'8 incident minutes. Verify arrival, capability, contact and Operations assignment.']};
    const [title,detail]=choices[a.type]||[a.type,'Records a correction against the actual resource picture.'];return {title,detail};
  }
  function ending(r){
    if(!r.finalState&&!Array.isArray(r.resources))return {title:'Your earlier response is preserved.',line:r.summary||'This archive contains the original decision record, without a final spatial snapshot.',areas:[],ready:null,callbacks:(r.history||[]).slice(-2).map(h=>({title:h.action,text:h.consequence})),constraints:r.constraints||[],question:'What would you change on another watch?',changed:r.variant===1?'Marsh demand becomes four sections; channel demand becomes three.':'Channel demand becomes four sections; marsh demand becomes three.'};
    const s=r.finalState,resources=s?.resources||r.resources||[],variant=r.variant===1?1:0;
    const intel=s?.intel||root.RR17.SCENARIOS[variant];
    const picture={resources,intel};const areas=containment(picture);
    const monitoring=resources.some(x=>x.kind==='monitor'&&x.capable&&x.verified&&x.status==='assigned'&&x.location==='Source berth');
    const relief=resources.some(x=>x.kind==='relief'&&x.verified&&x.status==='assigned'&&x.location==='Source berth');
    const ready=monitoring&&((r.minute||210)<180||relief),gap=areas.some(a=>a.boom.length<a.demand);
    const history=r.history||[],coupling=history.find(h=>h.source==='condition'&&['Reserve deployed','Coupling failure'].includes(h.action));
    const allocation=history.find(h=>h.source==='player'&&h.action==='Containment allocation');
    const source=history.find(h=>h.source==='player'&&h.action==='Monitoring source');
    const callbacks=[coupling||allocation,source||history.find(h=>h.source==='player')].filter(Boolean).map(h=>({id:h.id||null,title:time(h.minute)+' / '+h.action,text:h.consequence,carry:h.constraint}));
    if(source&&s){const arrival=history.find(h=>h.teamKey?.startsWith('receive:MON-')&&h.manifest?.assignment==='source');if(arrival)callbacks[1]={id:source.id,title:'Your sourcing choice',text:`The atmospheric team reached its source assignment at ${time(arrival.minute)}. ${s.flags.channelMonitoringGap?'The channel monitoring gap remains.':'Channel monitoring is in place.'}`};}
    const constraints=s?.intel?.currentGaps||r.constraints||[];
    return {title:ready?(gap?'The source has support. The coverage gap carries on.':'The next watch has a supported response.'):'The crew is still waiting. The next watch inherits the hold.',line:ready?'“We have the monitoring and crew cover at the berth. Keep the remaining limits in our handover.”':'“We know what is still missing at the berth. That stays at the front of our watch.”',areas,ready,callbacks,constraints,question:coupling?.action==='Reserve deployed'?'What changes if you put the spare in the channel instead?':coupling?'What changes if you hold one section back?':'What changes if you choose a different monitoring source?',changed:variant===0?'An ebb current shifts the higher demand to the channel: four sections there, three at the marsh.':'The current puts the marsh first: four sections there, three in the channel.'};
  }
  root.RR17Scenes={sourcing,containment,crewLine,scene,result,decision,recovery,ending,time};
})(globalThis);
