/* Pure presentation selectors. Incident truth stays in RR17. */
(function(root){
'use strict';
const time=n=>{n=420+Math.round(n);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;};
function sourcing(s){return root.RR17.VENDORS.filter(v=>v.capable).map(v=>({id:v.id,name:v.id==='internal'?'Move the channel team':v.id==='harbor'?'Bring in the fast team':'Use the regional team',supplier:v.name,cost:v.cost,eta:time(s.minute+v.eta),minutes:6,tradeoff:v.id==='internal'?'Arrives first; Channel Recovery loses monitoring.':v.id==='harbor'?'Keep channel monitoring; pay for faster source help.':'Keep channel monitoring; pay less, wait longer.',uncertainty:s.difficulty==='advanced'&&v.id==='regional'?'Quoted ETA; dispatch may revise the road transfer.':'Confirmed mobilization estimate.'}));}
function containment(s){return ['Marsh inlet','Channel'].map(location=>({location,boom:s.resources.filter(r=>r.kind==='boom'&&r.status==='assigned'&&r.location===location).map(r=>r.id),skimmers:s.resources.filter(r=>/skimmer/.test(r.kind)&&r.capable&&r.status==='assigned'&&r.location===location).map(r=>r.id),monitoring:s.resources.some(r=>r.kind==='monitor'&&r.verified&&r.status==='assigned'&&r.location===location),demand:location==='Channel'?s.intel.channelDemand:s.intel.marshDemand}));}
function crewLine(s){const r=s.resources.find(r=>r.id===s.flags.monitorId);return s.safetyHold?{from:'Entry Group',text:r?.status==='en_route'?`“We’re holding at the berth. ${r.name} is due at ${time(r.eta)}.”`:'“We cannot begin source work until monitoring and required crew coverage are verified.”'}:{from:'Entry Group',text:'“Monitoring is assigned at the berth. We can support source work while crew coverage holds.”'};}
function scene(s,selected){const t=s.tasks.find(t=>t.id===selected)||s.tasks.find(t=>s.queue.includes(t.id)&&t.available);return {task:t,crew:crewLine(s),areas:containment(s),sourceHeld:s.safetyHold,clock:time(s.minute),reserve:s.resources.filter(r=>r.kind==='boom'&&r.status==='available').length,failed:s.resources.filter(r=>r.kind==='boom'&&r.status==='out_of_service').map(r=>r.id),choices:sourcing(s)};}
root.RR17Scenes={sourcing,containment,crewLine,scene};
})(globalThis);
